### ISSUE TITLE
`_createEndpoint` natspec

### ISSUE THREAD

**Issue by alcueca** [chromaxyz/reflex#131]
Regular modules will deploy additional endpoints in the use case where a module implements a factory. When an external user calls a function like `deployPool` a new endpoint would be deployed, which uses some FactoryState storage and some FactoryModule code. The FactoryModule functions would work which pool is being used from the endpoint address with is appended by the Dispatcher as trailing calldata.

**Comment by zerosnacks** [comment]
> Regular modules will deploy additional endpoints in the use case where a module implements a factory. When an external user calls a function like `deployPool` a new endpoint would be deployed, which uses some FactoryState storage and some FactoryModule code. The FactoryModule functions would work which pool is being used from the endpoint address with is appended by the Dispatcher as trailing calldata.

I'm not sure if I entirely understand what you mean but I've added some extra NatSpec to the `_createEndpoint` function in #135. Let me know if it suffices.
